# Generated by Django 4.1.5 on 2023-01-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_currentrecipes_user_id_alter_history_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentrecipes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
