# Generated by Django 4.1.5 on 2023-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_week_recipes',
        ),
    ]
