# Generated by Django 4.1.5 on 2023-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_week_recipes',
            field=models.JSONField(),
        ),
    ]
