# Generated by Django 4.1.5 on 2023-01-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_current_week_recipes'),
        ('main', '0002_remove_user_current_week_recipes'),
    ]

    operations = [
    ]
