# Generated by Django 4.1.5 on 2023-01-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_current_week_recipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
